# Generated by Django 6.1.1 on 2026-09-20 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('lahir', models.DateTimeField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('label', models.TextField(max_length=200)),
            ],
        ),
    ]
