# Generated by Django 6.1.1 on 2026-09-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='almamater',
            field=models.CharField(blank=True, choices=[('Universitas Indonesia', 'universitas indonesia'), ('Universitas Gajah Mada', 'universitas gajah mada'), ('Institut Teknologi Bandung', 'institut teknologi bandung'), ('Universitas Monash', 'universitas monash')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='instrumen',
            field=models.CharField(blank=True, choices=[('Lainnya', 'lainnya'), ('Vokal', 'vokal'), ('RAP', 'rap')], null=True),
        ),
    ]
