# Generated by Django 6.1.1 on 2026-09-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_almamater_about_description_about_instrumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('Lagu', 'lagu'), ('vidio', 'Video')], max_length=199)),
                ('label', models.CharField(max_length=200)),
                ('judul', models.CharField(max_length=3330)),
                ('link', models.URLField(max_length=1223)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='genre',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='instrumen',
            field=models.CharField(blank=True, choices=[('Vokal', 'vokal'), ('Lainnya', 'lainnya'), ('RAP', 'rap')], null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
